### ISSUE TITLE
feat：defer实现可以支持多行，而不强行限定单个函数

### ISSUE THREAD

**Issue by 578223592** [youngyangyang04/KVstorageBaseRaft-cpp#13]
目前的Defer只能支持传入单个函数，这一点也不cool
参考：
https://github.com/OpenAtomFoundation/pika/blob/1a294d006063fd51390965d103fcba3c6ba65e3d/src/cache/src/list.cc#L107

**Comment by hero-heng** [comment]
这个我来实现一下

**Comment by 578223592** [comment]
> 这个我来实现一下

great!也许你可以给我一个完成的大概时间

**Comment by 578223592** [comment]
31日左右

**Comment by 578223592** [comment]
done. thanks to @hero-heng . #22 #23
