### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by fzdmm** [youngyangyang04/KVstorageBaseRaft-cpp#17]
KVstorageBaseRaft-cpp-rpc/src/rpc/include/rpcheader.pb.h:10:10: fatal error: google/protobuf/port_def.inc: No such file or directory

**Comment by 578223592** [comment]
可以提供更多的信息吗？比如你的版本号，或者你可以参考下：#8

**Comment by noanswerin** [comment]
运行这条命令sudo apt-get install libprotobuf-dev protobuf-compiler可以解决问题

**Comment by 578223592** [comment]
@fzdmm 时间有点久了，希望你的问题已经解决，我将关闭这条issue，如果还有问题随时欢迎重新打开
