### ISSUE TITLE
feat：RPC自定义协议的头部字段长度优化

### ISSUE THREAD

**Issue by 578223592** [youngyangyang04/KVstorageBaseRaft-cpp#19]
头部的_消息体长度_字段目前是固定4个字节，这个可能设计的不是很合理，考虑使用更灵活的方式。
可以参考protobuf的变长编码、Redis中的对于长度的变长编码，即用标志位来确定_消息体长度_,这样来节约RPC的长度

**Comment by ildnyy** [comment]
我想试一下解决这个issue

**Comment by 578223592** [comment]
> 我想试一下解决这个issue

非常欢迎。或许你可以告诉我你完成的日程安排，如果有任何相关问题可以继续在这里留言，非常乐意解答。

**Comment by ildnyy** [comment]
> > 我想试一下解决这个issue
> 
> 非常欢迎。或许你可以告诉我你完成的日程安排，如果有任何相关问题可以继续在这里留言，非常乐意解答。

请问项目中使用的muduo boost protobuf分别是什么版本的？我预计在二月底之前完成吧

**Comment by 578223592** [comment]
> > > 我想试一下解决这个issue
> > 
> > 
> > 非常欢迎。或许你可以告诉我你完成的日程安排，如果有任何相关问题可以继续在这里留言，非常乐意解答。
> 
> 请问项目中使用的muduo boost protobuf分别是什么版本的？我预计在二月底之前完成吧

我的版本信息在：https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/issues/8#issuecomment-1874857635

在正式写代码之前可以讨论下你的改进思路和原因，看下是否合理 。

问题就指派给你了

**Comment by 578223592** [comment]
@ildnyy hi，请问完成情况如何，如果有困难无法完成或者其他情况欢迎跟我沟通，如果你近期没有回复我，我可能会自己完成这个issue

**Comment by 578223592** [comment]
> > @ildnyy hi，请问完成情况如何，如果有困难无法完成或者其他情况欢迎跟我沟通，如果你近期没有回复我，我可能会自己完成这个issue
> 
> 已经改了，但是不是很懂怎么突出测试，但是原本的都能运行

@ildnyy 你可以先提交pr，然后在pr里面说明一下你的**主要改动**和**改动的原因（思路）**
