### ISSUE TITLE
当前raft是否支持持久化

### ISSUE THREAD

**Issue by TiNnNnnn** [youngyangyang04/KVstorageBaseRaft-cpp#21]
我看现在好像是支持文件持久化的，之后可以改成持久化到kv引擎中，比如leveldb

**Comment by 578223592** [comment]
目前是使用boost达到一个很粗的持久化，没有太多考量。
确实可以这样，不过这个项目的目的是学习raft，而不是追求性能，后期小概率会改到leveldb等现有的引擎，如果这块有更改多半是手搓一个简单的引擎这样。

**Comment by 578223592** [comment]
我关闭了这个issue，如果还有相关问题，随时欢迎reopen这个issue
