### ISSUE TITLE
请问这样算运行成功吗

### ISSUE THREAD

**Issue by noanswerin** [youngyangyang04/KVstorageBaseRaft-cpp#27]
provider文件运行如图
![VUEP04C$6A}5Q@BD)B07D88](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/97148347/ba476340-b99e-472c-a317-e42aab7063ea)

consumer文件运行如图
![(YQ ~%_2%AF6R(L{G@R`C3S](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/97148347/5118d8cf-8592-499c-853e-7d684ad5897c)

raftCoreRun文件运行如图，且文件一直运行
![S 4}E)9LQ~05C@1L3}ZR K2](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/97148347/b76d36a6-2d92-4da8-a6a2-703722ddc71f)

callermain文件如图，且retrun到0
![J86O1CJ9R~_~1R9Z`96N~}U](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/97148347/8fb1ba6f-5dba-462c-9807-ffb68e70e91d)

**Comment by 578223592** [comment]
yes.已经全部运行成功了。祝贺！（之前我在星球回复的时候记错了，误以为这样的显示有问题，实际没有问题）

欢迎分享下你的环境配置过程，以pr或者在这个issue继续留言都可以。

我将关闭这个issue，随时欢迎再打开。
