### ISSUE TITLE
make报错

### ISSUE THREAD

**Issue by Gump5236** [youngyangyang04/KVstorageBaseRaft-cpp#33]
您好，我在使用rpc时make出错
protobuf的版本 3.14.2 cmake版本3.22.6
![image](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/73152972/1ba27bc5-10a3-4514-b85d-de66d47e4968)
muduo库已经链接到/usr/下，boost也已安装，但是在make时报错一些代码相关的错误，我并未修改过代码，报错如下
![image](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/73152972/e4f1e051-019a-4ace-87a6-6673f8ae1caf)
我看报错信息，使用的
![image](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/73152972/05c5cc3a-fe24-4ed1-8431-12119fce768f)
我的g++和gcc版本是4.8.5的

**Comment by 578223592** [comment]
我看到你发起了另一个issue，也许这个问题已经解决了，你可以告诉我怎么解决的吗？
我将关闭这个issue，如果还有问题，欢迎再打开。

**Comment by Gump5236** [comment]
@578223592 解决方案如您所说，是我的gcc版本太低，升级之后就解决了！
