### ISSUE TITLE
make时报错

### ISSUE THREAD

**Issue by zhuyi1159** [youngyangyang04/KVstorageBaseRaft-cpp#43]
命令行无法直接安装protoc，我根据官方教程由源码编译安装了protoc-3.12.4
<img width="861" alt="image" src="https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/57618314/6f487526-78e8-4297-814a-9a8698f06e0e">
但是报了这个错误：
<img width="597" alt="image" src="https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/57618314/3228e273-d14f-42a0-ab8b-3d4c95646a44">
我看这个报错与安装muduo库时未将lib文件夹内容复制进usr/lib时的报错类似，但我在编译protoc时使用了bazel编译，没有对应的lib文件夹

**Comment by 578223592** [comment]
个人建议的方法1：
![image](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/65906820/08fa5059-e70d-4e89-8666-a9cebf8d1da9)
执行你图片中我截取的这部分命令。
2.在readme中更新一下安装，可以参考下，Ubuntu的话是一行命令

**Comment by zhuyi1159** [comment]
谢谢，已经解决了，我重新安装了protoc，执行了以下命令：
./configure
make && make install
