### ISSUE TITLE
没有生成test.conf

### ISSUE THREAD

**Issue by The-Great-Professor** [youngyangyang04/KVstorageBaseRaft-cpp#44]
make编译完之后只有可执行文件没有test.conf
![image](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/81975860/459ae38e-bb9d-43c3-8666-a42797175a2a)

**Comment by 578223592** [comment]
> make编译完之后只有可执行文件没有test.conf ![image](https://private-user-images.githubusercontent.com/81975860/309806737-459ae38e-bb9d-43c3-8666-a42797175a2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1OTg1MzAsIm5iZiI6MTcwOTU5ODIzMCwicGF0aCI6Ii84MTk3NTg2MC8zMDk4MDY3MzctNDU5YWUzOGUtYmI5ZC00M2MzLTg2NjYtYTQyNzk3MTc1YTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDAwMjM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MmExOTE1Mzk5ZTZlOThiYTM2ZTYzZGE1YjdiMmU4NDBhNTQwZGFjYWExYTM5Yzk5Mzc0MTQ4NDBmYjEzNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9VhAO5G8ZZZsMz8kcSPXk1XJC8iE4veE56G-Kejx5sQ)

@The-Great-Professor 
sry，不小心移除了test.conf文件，目前添加回来了
1.可以拉取最新的更新；
2.可以自己在bin目录创建文件`test.conf`添加如下内容：
```
node0ip=192.168.116.128
node1ip=192.168.116.128
node1port=15619
node0port=15618
node2ip=192.168.116.128
node2port=15620
```
运行如果端口冲突了，可以尝试重启程序或者手动更换。

**Comment by 578223592** [comment]
@The-Great-Professor  
我关闭这个issue了，如果仍有任何问题欢迎再打开。
