### ISSUE TITLE
请问怎么分析火焰图

### ISSUE THREAD

**Issue by diadestiny** [youngyangyang04/KVstorageBaseRaft-cpp#46]
我导出了这个火焰图，这个图好像没有定量指标（只有定性占比），请问关于测试性能方面的话是怎么分析呢
![image](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/44188454/01390826-5a97-430c-82c8-bdd9ec60eb81)

**Comment by 578223592** [comment]
火焰图的分析网上，这里就不献丑展开了，个人认为分析关键点就是看下占比比较大的函数块有没有不正常的？即比你想象的占比更大。

**Comment by 578223592** [comment]
@diadestiny  https://github.com/578223592/sylar-from-scratch-comment/blob/comment/doc/%E5%8E%9F%E7%94%9F%E6%B5%8B%E8%AF%95%E7%BB%93%E6%9E%9C%E5%8F%8A%E5%88%86%E6%9E%90.md
链接里面是我分析协程项目的过程记录，希望对你有帮助。

----
我关闭这个issue了，有任何问题欢迎再打开。
