### ISSUE TITLE
Raft::sendRequestVote函数中RequestVote的来源问题

### ISSUE THREAD

**Issue by Anu-orange** [youngyangyang04/KVstorageBaseRaft-cpp#47]
想询问一下在Raft::sendRequestVote函数中调用了RequestVote函数，该函数是调用的哪个函数，内部是怎么实现的？？
![019470a8a20cc3948632ea4c8cf75b6](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/86885288/bf0adfbf-ff4a-45fc-b197-668714134c6a)

**Comment by 578223592** [comment]
@Anu-orange 
如果你点进去就可以看到：
![image](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/65906820/d60a4d60-f9e6-471a-b5df-3ea49f5067c4)
这部分是rpc的调用，其中最关键的是
```
stub_->RequestVote(&controller, args, response, nullptr);
```
这相当于调用了rpc的方法，对端接收到rpc后会调用：
![image](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/65906820/9d6ca759-4181-4e25-b659-db255b9aa1be)
，这个方法很简单，就是调用本机的RequestVote方法。
**因此这个方法的功能就是通过RPC调用远端的RequestVote方法。**

**Comment by Anu-orange** [comment]
@578223592 
我好像明白您的意思了，意思就是stub_->RequestVote(&controller, args, response, nullptr)这个函数是由发起投票请求的Candidate调用的，而Raft::RequestVote这个函数是由接收请求的节点follower调用的对吧

**Comment by 578223592** [comment]
> @578223592 我好像明白您的意思了，意思就是stub_->RequestVote(&controller, args, response, nullptr)这个函数是由发起投票请求的Candidate调用的，而Raft::RequestVote这个函数是由接收请求的节点follower调用的对吧

YES @Anu-orange

**Comment by Anu-orange** [comment]
@578223592 
好的 谢谢您

**Comment by 578223592** [comment]
我关闭这个issue了，如果有相关的任何问题，欢迎再打开。
