### ISSUE TITLE
关于Raft测试

### ISSUE THREAD

**Issue by diadestiny** [youngyangyang04/KVstorageBaseRaft-cpp#54]
您好，想请问下从功能的角度怎么测试能证明本项目Raft分布式的正确性，有什么工具还是需要怎么实现呢

**Comment by 578223592** [comment]
raft的功能测试确实是一个非常重要且非常难的环节，本项目目前并没有相关的测试。
本项目基本是按照mit6.824的课程修改的，因此最开始使用的是go语言完成的课程内容并保证正确性，大概的方式就是通过控制节点宕机并记录提交的命令的返回值来判断是否正确。
如果对测试部分有更多建议欢迎pr
