### ISSUE TITLE
raft调用InstallSnapshot存在重复的问题

### ISSUE THREAD

**Issue by Pyolar** [youngyangyang04/KVstorageBaseRaft-cpp#57]
![Snipaste_2024-04-10_14-48-52](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/107487384/8221cc3e-dc47-43ed-860a-0077b287190c)
这里为什么要向kvserver推送两次安装的日志信息

**Comment by 578223592** [comment]
@Pyolar 感谢指出，这里确实存在重复推送的问题。
简单的删除下放代码所在行应该就可以了。
```
  applyChan->Push(msg);
```
如果你想来一个贡献，欢迎pr。
或者我会删除它。
