### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Gu-Hao1** [youngyangyang04/KVstorageBaseRaft-cpp#59]
[  1%] Building CXX object CMakeFiles/skip_list_on_raft.dir/src/rpc/mprpcchannel.cpp.o
In file included from /home/gu/K-V存储数据库-demo/KVstorageBaseRaft-cpp-main/src/rpc/mprpcchannel.cpp:9:
/home/gu/K-V存储数据库-demo/KVstorageBaseRaft-cpp-main/src/rpc/include/rpcheader.pb.h:10:10: fatal error: google/protobuf/port_def.inc: 没有那个文件或目录
   10 | #include <google/protobuf/port_def.inc>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/skip_list_on_raft.dir/build.make:76：CMakeFiles/skip_list_on_raft.dir/src/rpc/mprpcchannel.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:334：CMakeFiles/skip_list_on_raft.dir/all] 错误 2
make: *** [Makefile:91：all] 错误 2
请问如何解决
![error](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/168436678/818342f5-1acd-430b-9b6e-d9500ba437df)

**Comment by 578223592** [comment]
please look at https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/issues/30 first.

**Comment by 578223592** [comment]
@Gu-Hao1 没问题我先关闭了，又需要你可以再开启这个issue
