### ISSUE TITLE
在rpc中创建cmake-build-debug执行cmake成功,bin文件夹没有生成对应的可执行文件

### ISSUE THREAD

**Issue by JanAthena1999** [youngyangyang04/KVstorageBaseRaft-cpp#60]
![Snipaste_2024-05-08_21-41-47](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/50019934/a3384370-82c8-4540-b1db-809c978ed9dc)
![Snipaste_2024-05-08_21-46-48](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/50019934/c4f9282b-91bf-43b4-99c6-7116b0d90fa6)

**Comment by DUTRB** [comment]
cmake-build-debug应该新建在根文件目录，第一步使用 cmake .. 命令，然后 make，看你图片里文件位置和第一步操作好像不对。
![2024-05-10_14-44-32](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/104288927/054141f5-24ef-4fe6-85b9-bbf0c6b3b038)

**Comment by 578223592** [comment]
还有问题欢迎随时重新打开这个issue @JanAthena1999
