### ISSUE TITLE
make遇到了如下问题

### ISSUE THREAD

**Issue by reversible67** [youngyangyang04/KVstorageBaseRaft-cpp#62]
你好，我是在centos下构建项目的，我在make时 遇到了如下问题  尝试了很久发现还是不会解决 所以来请教一下大家！
![image](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/145561589/e17a7585-363d-42b6-955c-5039ac30219e)

**Comment by 578223592** [comment]
看起来像是没有正确安装boost库。
@reversible67

**Comment by Zzz913977094** [comment]
请问解决了吗，我也是遇到了相同的问题

**Comment by 578223592** [comment]
还有问题欢迎随时重新打开这个issue @reversible67  @Zzz913977094
