### ISSUE TITLE
raftCoreRun运行出问题

### ISSUE THREAD

**Issue by 297952** [youngyangyang04/KVstorageBaseRaft-cpp#64]
provider和consumer执行后如图所示，
![68aa14a3b3b3c985ea974805a6e71a9](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/169135997/49f135eb-4003-469d-9f5f-e6ea4a971395)
而raftCoreRun运行后提示的是
format: command -n <nodeNum> -f <configFileName>
![2](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/169135997/2b225d99-9e5d-4667-af6e-c1cd78a78abd)

**Comment by 578223592** [comment]
@297952  README中有说明：
```
// make sure you in bin directory ,and this has a test.conf file
raftCoreRun -n 3 -f test.conf
```

**Comment by 578223592** [comment]
@297952 没问题我先关闭了，又需要你可以再开启这个issue****
