### ISSUE TITLE
请教：安装muduo时出现错误，但貌似确实安装了protobuf，求教排查与解决方法

### ISSUE THREAD

**Issue by fucccx** [youngyangyang04/KVstorageBaseRaft-cpp#66]
![Uploading 112.png…]()

**Comment by fucccx** [comment]
![111](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/116435428/687c0162-44c9-4fa6-b6f1-f0070e85c967)

**Comment by fucccx** [comment]
![112](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/116435428/8445a592-be6e-4781-af80-099b1b64cf14)

**Comment by 578223592** [comment]
@fucccx muduo库的安装和protobuf库没有关系，但是muduo好像是依赖boost的，你可以往这个方向排查一下

**Comment by 578223592** [comment]
@fucccx 还有问题欢迎随时重新打开这个issue
