### ISSUE TITLE
util.h文件中的模板函数format

### ISSUE THREAD

**Issue by Pyolar** [youngyangyang04/KVstorageBaseRaft-cpp#67]
![微信图片_20240607164345](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/107487384/6ceea5af-7f3b-44cc-9d3e-1d5982b9e51d)
是不是没用到格式化字符串，后面调用myAssert的时候输出的是不是就只有可变长度的参数信息，而不是包含格式化字符串以及可变长度的参数

**Comment by 578223592** [comment]
@Pyolar 抱歉回复的晚。

这段代码写的时候应该参考了printf函数的实现。

> 后面调用myAssert的时候输出的是不是就只有可变长度的参数信息，而不是包含格式化字符串以及可变长度的参数

调用myAssert的时候输出是格式化完毕后的字符串，你可以改写代码尝试一下

**Comment by Pyolar** [comment]
@578223592 
![微信图片_20240621093133](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/107487384/1196a096-e5ac-4049-bd2d-1c9be0693f43)
在clion上运行这个函数，输出的也不是格式化完毕的字符串，难道我调用的有问题吗

**Comment by 578223592** [comment]
@Pyolar 看起来代码是有问题的，没有正确的格式化。
非常感谢提出这个问题。
如果有时间，也欢迎提交一个pr来修正这个问题。
