### ISSUE TITLE
请问 raftCoreRun无法运行怎么解决

### ISSUE THREAD

**Issue by nianxiaogao** [youngyangyang04/KVstorageBaseRaft-cpp#69]
![问题1](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/124337309/94c77c1f-2b9d-4392-8363-8a92dacd816d)

**Comment by nianxiaogao** [comment]
找到解决办法了

**Comment by 578223592** [comment]
@nianxiaogao 才看到，应该是`./文件名`。解决了我就关闭这个issue了
