### ISSUE TITLE
运行rpc分支时，comsumer会不停的报connect fail的错误

### ISSUE THREAD

**Issue by StrongMak** [youngyangyang04/KVstorageBaseRaft-cpp#7]
想问一下单单是run  rpc这一块，我把con pro跑起来后，con一直connect fail是啥原因呀，我是用docker上的linux，ubuntu22跑的，会和端口啥的有关系吗，谢谢解答![image](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/123240046/c104a59f-4062-4186-916e-d2e671b7db17)

**Comment by 578223592** [comment]
抱歉回复的晚
可能会跟端口有关系，你需要注意下面这几点：
1.先开provider，再开consumer
2.两个程序运行在一个地方（一个docker）
3.确定provider监听已经打开，运行后类似于下图
![image](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/65906820/23ea1f2f-3b04-41ce-8256-19cd524dd836)
其中
![image](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/65906820/d562b50a-92c4-41b9-a48c-0701aecda509)
看出已经成功监听

**Comment by 578223592** [comment]
我关闭这个issue了，如果还有问题，欢迎随时重新打开或者创建新的issue提问。 @StrongMak
