### ISSUE TITLE
请教MprRpc 命名，求解答

### ISSUE THREAD

**Issue by fucccx** [youngyangyang04/KVstorageBaseRaft-cpp#72]
您好我刚开始学习分布式的相关知识，是小白，在星球中看到您给RPC通信框架命名为“MprRpc”，这只是一个自定义的名字吗，意图区别网上的“mprpc”吗，求解答跪谢

**Comment by 578223592** [comment]
> 您好我刚开始学习分布式的相关知识，是小白，在星球中看到您给RPC通信框架命名为“MprRpc”，这只是一个自定义的名字吗，意图区别网上的“mprpc”吗，求解答跪谢

@fucccx 没有什么区别，大概只是当时学习了这个库就用了。
我将issue关闭了，有问题你可以再打开。
