### ISSUE TITLE
make命令无法正常运行

### ISSUE THREAD

**Issue by volaking** [youngyangyang04/KVstorageBaseRaft-cpp#8]
您好，我在执行make命令时会产生大量报错，在其他的代码上没有出现过这种现象。上网搜索了下原因，可能是与protobuf库相关，也许是版本与代码不兼容等问题，我尝试着重新安装了protobuf，但make命令仍然报错，请问应该怎么解决这个问题，能否给我一些建议呢。

ubantu版本：Ubuntu 20.04.6 LTS
cmake版本：3.28.1

下面是部分报错内容：
[  3%] Building CXX object CMakeFiles/skip_list_on_raft.dir/src/rpc/mprpcchannel.cpp.o
In file included from /usr/include/google/protobuf/map_entry_lite.h:36,
                 from /usr/include/google/protobuf/generated_message_table_driven.h:35,
                 from /home/zhaozhuo/code/git/KVstorageBaseRaft-cpp/src/rpc/include/rpcheader.pb.h:26,
                 from /home/zhaozhuo/code/git/KVstorageBaseRaft-cpp/src/rpc/mprpcchannel.cpp:3:
/usr/include/google/protobuf/stubs/casts.h: In function ‘To google::protobuf::internal::bit_cast(const From&)’:
/usr/include/google/protobuf/stubs/casts.h:118:25: error: ‘bit_cast_with_different_sizes’ was not declared in this scope
  118 |                         bit_cast_with_different_sizes);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/stubs/casts.h:117:3: error: there are no arguments to ‘GOOGLE_COMPILE_ASSERT’ that depend on a template parameter, so a declaration of ‘GOOGLE_COMPILE_ASSERT’ must be available [-fpermissive]
  117 |   GOOGLE_COMPILE_ASSERT(sizeof(From) == sizeof(To),
      |   ^~~~~~~~~~~~~~~~~~~~~

![image](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/assets/142475898/1748e43c-6cce-4d47-a11d-953f1178f079)

**Comment by 578223592** [comment]
你的protobuf的版本是多少？我认为这个比较重要
我这里给出我的版本信息：
protobuf
```
protoc --version                      
libprotoc 3.12.4
```
ubuntu
```
lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```
cmake
```
cmake --version    
cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by 578223592** [comment]
> 感谢您的建议，我按照您的版本重新安装了ubuntu和其他的库，现在可以成功运行了。 ![image](https://private-user-images.githubusercontent.com/142475898/294181826-eb27ac14-0888-4600-9975-08895940ed9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNzMwMTUsIm5iZiI6MTcwNDM3MjcxNSwicGF0aCI6Ii8xNDI0NzU4OTgvMjk0MTgxODI2LWViMjdhYzE0LTA4ODgtNDYwMC05OTc1LTA4ODk1OTQwZWQ5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxMjUxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDMxYmQxYTdjYzBjNjk4ZTIyMGI4MjJmNDFlYmI2YThhZmJiMjAyOGYxZjkzMThkZjk2NTBlZWVhYmRhZDk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZCU38aP20nMOjpW_3tPW-96Kc8OebdHSkLP2lz5sunU)

nice！！！
**如果有时间欢迎分享一下你的环境安装过程，非常感谢。**
我将关闭这个issue，如果有任何问题，欢迎再次打开提问。

**Comment by jueshixian** [comment]
补充：用源码编译和用命令行安装，anaconda中的protobuf冲突解决方案：https://blog.csdn.net/lilai619/article/details/105997911
