### ISSUE TITLE
make时报错

### ISSUE THREAD

**Issue by Europa-Clipper** [youngyangyang04/KVstorageBaseRaft-cpp#82]
Ubuntu上装好了boost，protoc3.6.1，muduo。现在拿着一堆文件不知道怎么运行，真诚求各位大佬指点！😂

**Comment by Europa-Clipper** [comment]
![image](https://github.com/user-attachments/assets/bbeb5e7a-2553-40ef-82f4-5de27f8ee877)make时报错

**Comment by kakeelee** [comment]
> ![image](https://private-user-images.githubusercontent.com/109334276/365126887-bbeb5e7a-2553-40ef-82f4-5de27f8ee877.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MDIyNTMsIm5iZiI6MTcyNTcwMTk1MywicGF0aCI6Ii8xMDkzMzQyNzYvMzY1MTI2ODg3LWJiZWI1ZTdhLTI1NTMtNDBlZi04MmY0LTVkZTI3ZjhlZTg3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwN1QwOTM5MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjZmMDZhZjRmMDllZjUyYzdhZTFjZGEzZjIxNzhlZjkwZTM4ODczYjA1YTcyOWVmMjZhYzc5MDY1MmQzNDFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r4ds1Q3Yw1Wl7mNW4gndq3REqQ-nkPMzOwIjrOFVauY)make时报错

应该是protocbuf没装好，检查一下`/usr/local/include/google/protobuf/port_def.inc`是否有这个文件

**Comment by 578223592** [comment]
@Europa-Clipper 环境安装问题可以先看一下：https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/issues/30，还有就是安装环境建议按照readme的步骤来。

**Comment by Europa-Clipper** [comment]
> @Europa-Clipper 环境安装问题可以先看一下：[https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/issues/30，还有就是安装环境建议按照readme的步骤来。](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/issues/30%EF%BC%8C%E8%BF%98%E6%9C%89%E5%B0%B1%E6%98%AF%E5%AE%89%E8%A3%85%E7%8E%AF%E5%A2%83%E5%BB%BA%E8%AE%AE%E6%8C%89%E7%85%A7readme%E7%9A%84%E6%AD%A5%E9%AA%A4%E6%9D%A5%E3%80%82)
我再去研究一下，谢谢大佬！

**Comment by 578223592** [comment]
@Europa-Clipper 看一下还有没有问题哈。已经两周了，我先把这个issue关闭了，有需要可以随便再打开。

**Comment by kebukeYi** [comment]
运行安装指导: https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/tree/raft_DB
