### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by Iris-n** [youngyangyang04/KVstorageBaseRaft-cpp#84]
使用rpc报错，运行make之后出现如下：
<img width="419" alt="1726478634825" src="https://github.com/user-attachments/assets/007caf00-96f4-4615-93c7-08f7ecdd49b0">
<img width="430" alt="1726478657033" src="https://github.com/user-attachments/assets/7156179c-0f46-4b56-be6a-1069c99b91cd">

**Comment by AE86-SY** [comment]
看了之前的问题已解决，不知道怎么删
