### ISSUE TITLE
protobuf版本问题

### ISSUE THREAD

**Issue by kaoxirui** [youngyangyang04/KVstorageBaseRaft-cpp#85]
我的gazebo需要protobuf3.6版本，之前使用3.12.4版本确实能编译通过并使用，但是会影响我其他的使用。如果共存的多版本protobuf。请问在哪里指定protobuf的路径，在cmakelists中我好像没看见

**Comment by 578223592** [comment]
> 我的gazebo需要protobuf3.6版本，之前使用3.12.4版本确实能编译通过并使用，但是会影响我其他的使用。如果共存的多版本protobuf。请问在哪里指定protobuf的路径，在cmakelists中我好像没看见

@kaoxirui 这个库没有提供指定版本的能力。实际上我也不清楚如何指定。
此外理论上来说如果你正常安装了protobuf3.6，那么你可以尝试重新生成pb文件，也可以正常运行。
> 如果有兴趣，欢迎提交个pr来帮助这个项目提供指定protobuf版本的能力。
