### ISSUE TITLE
请教一下关于项目的理解以及从头开始创作的问题

### ISSUE THREAD

**Issue by zheyangdetaiyang** [youngyangyang04/KVstorageBaseRaft-cpp#88]
因为我以前没有做项目的经历，对于项目创作的过程也不了解，在跟着大佬在代码随想录上的文章进行学习的时候不知道该怎么进行，比如各个函数间的相互调用的思路，以及各个类的定义等方面，想问一下各位分布式存储的项目从零开始的话应该怎么学习，我看大佬说这个项目是在mit6.824的基础上改过来的，我是应该去看一下课程和raft的相关流程吗

**Comment by zheyangdetaiyang** [comment]
现在是看到了大佬文章的05，但是对于源码中的各个文件的相互调用的关系不明白

**Comment by 578223592** [comment]
@zheyangdetaiyang 隔离每部分来看吧。比如你想看选举过程中的term的变化之类的东西，这时候就不要去看rpc干了什么，这样隔离的话看起来会轻松很多。

**Comment by 578223592** [comment]
@zheyangdetaiyang 我先关闭这个issue了哈，如果还有问题，👏🏻欢迎再提问，希望能帮到你
