### ISSUE TITLE
编译时有问题，DEFER宏有问题，麻烦能解答一下吗？

### ISSUE THREAD

**Issue by lshuaishuai** [youngyangyang04/KVstorageBaseRaft-cpp#90]
![微信图片_20241114173012](https://github.com/user-attachments/assets/26475464-aef6-4c13-bfa1-106e1bb70281)
chu'xian编译时有问题，DEFER宏有问题，麻烦能解答一下吗？

**Comment by 578223592** [comment]
@lshuaishuai 先看这里https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/issues/30。
此外，大概率是gcc版本问题，升级一下之类的

**Comment by lshuaishuai** [comment]
> @lshuaishuai 先看这里[https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/issues/30。](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/issues/30%E3%80%82) 此外，大概率是gcc版本问题，升级一下之类的

![image](https://github.com/user-attachments/assets/dc18766c-60cb-4820-a536-fa570320c4ae)

感谢你弄的回答，这是我的gcc版本，8.3.1，请问您的版本是多少呢？

**Comment by 578223592** [comment]
> > @lshuaishuai 先看这里[https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/issues/30。](https://github.com/youngyangyang04/KVstorageBaseRaft-cpp/issues/30%E3%80%82) 此外，大概率是gcc版本问题，升级一下之类的
> 
> ![image](https://private-user-images.githubusercontent.com/147410166/386418531-dc18766c-60cb-4820-a536-fa570320c4ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NjQ5NzMsIm5iZiI6MTczMTg2NDY3MywicGF0aCI6Ii8xNDc0MTAxNjYvMzg2NDE4NTMxLWRjMTg3NjZjLTYwY2ItNDgyMC1hNTM2LWZhNTcwMzIwYzRhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxNzMxMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04N2NhMTBkMjllMTViMTA4MzMxODZmZWQ4YzcwZjdiOWM3MzExZmU0ZmViMDY0OGFhMzUxNWZmZGI0MDNlM2U5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RCADSimvTM1kkUy9pbD3Ao9qveaLq0Jif9F-8xLRdUM)
> 
> 感谢你弄的回答，这是我的gcc版本，8.3.1，请问您的版本是多少呢？

这个版本试下
```
(base) ➜  ~ gcc --version
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
