### ISSUE TITLE
安装时库文件问题

### ISSUE THREAD

**Issue by LeeYSK** [youngyangyang04/KVstorageBaseRaft-cpp#91]
![错误](https://github.com/user-attachments/assets/87e16648-c4c6-4b5b-b054-af77c9306c5b)
在 安装 protoc 阶段，总是 make 不过去，一直报找不到 goole/protobuf/... 下的某个文件，为什么呢，我的 Ubantu 是 18, 我自己找了一些 protocbuf 的包安装也还是不行

**Comment by bingdouwang** [comment]
我也遇到同样的问题 去找了3.12.4的安装包，发现include下根本没有报错的这个文件

**Comment by bingdouwang** [comment]
解决了，去protobuf仓库下载源代码https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.4，然后参考这个https://blog.csdn.net/qq_46490027/article/details/128570526进行安装和配置环境变量，再在项目CMakeList.txt文件添加两行link_directories(/usr/local/protobuf/lib)     include_directories(/usr/local/protobuf/include/) 就可以编译成功了，路径中间的protobuf可能需要根据你的配置替换一下

**Comment by 578223592** [comment]
> 解决了，去protobuf仓库下载源代码[https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.4，](https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.4%EF%BC%8C) 要下载 protobuf-all-3.12.4.zip，然后参考这个[https://blog.csdn.net/qq_46490027/article/details/128570526进行安装和配置环境变量，再在项目CMakeList.txt文件添加两行link_directories(/usr/local/protobuf/lib)](https://blog.csdn.net/qq_46490027/article/details/128570526%E8%BF%9B%E8%A1%8C%E5%AE%89%E8%A3%85%E5%92%8C%E9%85%8D%E7%BD%AE%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%EF%BC%8C%E5%86%8D%E5%9C%A8%E9%A1%B9%E7%9B%AECMakeList.txt%E6%96%87%E4%BB%B6%E6%B7%BB%E5%8A%A0%E4%B8%A4%E8%A1%8Clink_directories(/usr/local/protobuf/lib)) include_directories(/usr/local/protobuf/include/) 就可以编译成功了，路径中间的protobuf可能需要根据你的配置替换一下

@bingdouwang 很棒，感谢 。 同时cc @LeeYSK ，看下是否能解决，如果还有问题可以再打开这个issue哈。
